# Generated by Django 2.1.4 on 2018-12-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20181224_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_image',
            field=models.ImageField(default='car.jpg', height_field=300, upload_to='', width_field=300),
        ),
    ]
